module BlockTypes
  BLOCK_TYPES = {
    'navigation'       => { name: 'Navigation',           icon: '📍', category: 'layout' },
    'ribbon'           => { name: 'Announcement Bar',     icon: '🎀', category: 'layout' },
    'hero'             => { name: 'Hero Section',         icon: '🎯', category: 'hero' },
    'hero_split'       => { name: 'Hero — Split',         icon: '⬛', category: 'hero' },
    'hero_centered'    => { name: 'Hero — Centered',      icon: '⬜', category: 'hero' },
    'hero_fullbleed'   => { name: 'Hero — Full Bleed',    icon: '🖼️', category: 'hero' },
    'sub_hero'         => { name: 'Sub Hero Carousel',    icon: '📋', category: 'hero' },
    'category_grid'    => { name: 'Category Grid',        icon: '🗂️', category: 'shop' },
    'product_grid'     => { name: 'Product Grid',         icon: '🛍️', category: 'shop' },
    'product_card'     => { name: 'Product Card',         icon: '🏷️', category: 'shop' },
    'featured_products'=> { name: 'Featured Products',    icon: '⭐', category: 'shop' },
    'new_products'     => { name: 'New Arrivals',         icon: '✨', category: 'shop' },
    'sales'            => { name: 'Deals & Specials',     icon: '💰', category: 'shop' },
    'brands'           => { name: 'Brands Carousel',      icon: '🏢', category: 'shop' },
    'brand_spotlight'  => { name: 'Brand Spotlight',      icon: '🔦', category: 'shop' },
    'strain_types'     => { name: 'Shop by Strain',       icon: '🌿', category: 'shop' },
    'promo_section'    => { name: 'Promo Banner',         icon: '🎊', category: 'marketing' },
    'promotional'      => { name: 'Editorial Promo',      icon: '🎁', category: 'marketing' },
    'cta'              => { name: 'Call to Action',       icon: '📣', category: 'marketing' },
    'email_optin1'     => { name: 'Newsletter + Image',   icon: '📧', category: 'marketing' },
    'email_optin2'     => { name: 'Newsletter Centered',  icon: '✉️', category: 'marketing' },
    'text_block'       => { name: 'Text Block',           icon: '📝', category: 'content' },
    'faq'              => { name: 'FAQ Accordion',        icon: '❓', category: 'content' },
    'faq_v2'           => { name: 'FAQ + Image',          icon: '❔', category: 'content' },
    'about_section'    => { name: 'About Section',        icon: '💡', category: 'content' },
    'contact_section'  => { name: 'Contact Section',      icon: '📞', category: 'content' },
    'footer'           => { name: 'Footer',               icon: '⬇️', category: 'layout' },
    'footer2'          => { name: 'Footer v2',            icon: '⏬', category: 'layout' },
    'age_gate'         => { name: 'Age Verification',     icon: '🔒', category: 'layout' }
  }.freeze
end
